[project]
name = "llm"
version = "0.1.0"
description = "A very simple LLM"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "humanize>=4.12.1",
    "numpy>=2.2.3",
    "torch>=2.6.0",
]
